import type { Metadata } from "next";
import { Cormorant_Garamond, Jost, DM_Mono } from "next/font/google";

import { siteUrl } from "@/lib/site-url";

import "./globals.css";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  style: ["normal", "italic"],
  variable: "--font-cormorant",
  display: "swap",
});

const jost = Jost({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-jost",
  display: "swap",
});

const dmMono = DM_Mono({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-dm-mono",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl()),
  title: "Luna Art Studio — Fine Art & Creative Classes",
  description:
    "Luna Art Studio offers fine art exhibitions, painting and drawing classes, and a vibrant creative community. Explore our gallery and join our weekly classes.",
  keywords:
    "art studio, painting classes, drawing, fine art, art gallery, creative classes, Warren NJ, New Jersey",
  openGraph: {
    title: "Luna Art Studio",
    description: "Fine Art & Creative Classes — Warren, NJ",
    type: "website",
    siteName: "Luna Art Studio",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Luna Art Studio",
    description: "Fine Art & Creative Classes — Warren, NJ",
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "48x48" },
      { url: "/icon.png", type: "image/png", sizes: "48x48" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
    shortcut: "/favicon.ico",
  },
  // openGraph.images / twitter.images: auto-generated by
  // `app/opengraph-image.tsx` and `app/twitter-image.tsx` (re-export).
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cormorant.variable} ${jost.variable} ${dmMono.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
