import type { Metadata } from "next";
import { Cormorant_Garamond, Jost, DM_Mono } from "next/font/google";

import { siteUrl } from "@/lib/site-url";

import "./globals.css";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  style: ["normal", "italic"],
  variable: "--font-cormorant",
  display: "swap",
});

const jost = Jost({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-jost",
  display: "swap",
});

const dmMono = DM_Mono({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  variable: "--font-dm-mono",
  display: "swap",
});

const baseUrl = siteUrl();

const organizationJsonLd = {
  "@context": "https://schema.org",
  "@type": "ArtGallery",
  name: "Luna Art Studio",
  url: baseUrl,
  logo: `${baseUrl}/luna.jpg`,
  image: `${baseUrl}/luna.jpg`,
  address: {
    "@type": "PostalAddress",
    streetAddress: "258 King George Rd, 2nd Floor",
    addressLocality: "Warren",
    addressRegion: "NJ",
    postalCode: "07059",
    addressCountry: "US",
  },
};

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),
  title: "Luna Art Studio — Fall Enrollment Open | Fine Art Classes",
  description:
    "Fall 2026 enrollment is open at Luna Art Studio in Warren, NJ. Wednesday art classes: Session 1 starts Sep 9 (9 classes), Session 2 Nov 11 – Feb 3. Register now.",
  keywords:
    "art studio, fall art classes, painting classes, drawing, fine art, art gallery, creative classes, Warren NJ, New Jersey, fall enrollment",
  openGraph: {
    title: "Luna Art Studio",
    description: "Fall 2026 Enrollment Open — Wednesday art classes in Warren, NJ",
    type: "website",
    siteName: "Luna Art Studio",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Luna Art Studio",
    description: "Fall 2026 Enrollment Open — Wednesday art classes in Warren, NJ",
  },
  icons: {
    icon: [
      { url: `${baseUrl}/favicon.ico`, sizes: "any" },
      { url: `${baseUrl}/icon-48.png`, type: "image/png", sizes: "48x48" },
      { url: `${baseUrl}/icon-96.png`, type: "image/png", sizes: "96x96" },
      { url: `${baseUrl}/icon-192.png`, type: "image/png", sizes: "192x192" },
    ],
    apple: [
      {
        url: `${baseUrl}/apple-touch-icon.png`,
        sizes: "180x180",
        type: "image/png",
      },
    ],
    shortcut: `${baseUrl}/favicon.ico`,
  },
  manifest: "/site.webmanifest",
  other: {
    "msapplication-TileImage": `${baseUrl}/icon-192.png`,
    "msapplication-TileColor": "#7a8c7e",
  },
  // openGraph.images / twitter.images: auto-generated by
  // `app/opengraph-image.tsx` and `app/twitter-image.tsx` (re-export).
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cormorant.variable} ${jost.variable} ${dmMono.variable}`}
    >
      <body>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(organizationJsonLd),
          }}
        />
        {children}
      </body>
    </html>
  );
}
